### ISSUE TITLE
TypeError: '>=' not supported between instances of 'numpy.ndarray' and 'str'

### ISSUE THREAD

**Issue by UnderTheCraft** [cphyc/matplotlib-label-lines#18]
Hey, I'm getting this error when adding labelLines to my plot (see image). Can you help me?

![image](https://user-images.githubusercontent.com/12684183/75051612-7fa90180-54ce-11ea-96ab-d1dc08367227.png)

**Comment by cphyc** [comment]
Hi!
Do you also have the error if you only try to plot `plt.plot(jan_plt['wh'], label='jan')`? Also, could you share what `jan_plt` is? Is it an array? A pandas dataframe?

**Comment by UnderTheCraft** [comment]
Hi, thank you for your quick answer.
Yes, I also get the error if I only plot the first one. Jan_plt is a pandas dataframe with the mean energy consumption of a household aggregated for the weekdays.
In the image below you can see further information.

![image](https://user-images.githubusercontent.com/12684183/75235329-5503c500-57bc-11ea-9134-2c4604fd7568.png)

Thanks in advance and regards :)

**Comment by cphyc** [comment]
Hi,
The error is due to a poor support of time series by this package. I never work with times series, so I don't know off-hand how to solve your issue. I guess that one solution would be to convert the index (Monday to Sunday) to a float-represented array before passing it to `labelLines`.
If you manage to get it to work, would you mind submitting a PR or sharing the snippet that solved your issue on this page?

**Comment by UnderTheCraft** [comment]
Ok, so as suggested I converted the weekday names back to a numerical format, by mapping the index of the dataframe. Now the label is illustrated correctly.

Maybe not the prettiest workaround, but it's fine for my case. Thanks a lot!

![image](https://user-images.githubusercontent.com/12684183/75440294-d2b20700-595b-11ea-9db4-9901a71bda47.png)
