### ISSUE TITLE
How can i add labels to the circles with radius size?

### ISSUE THREAD

**Issue by syedhamidali** [cphyc/matplotlib-label-lines#53]
```python
t = np.linspace(0,2*np.pi)
A = [10,25]
fig = plt.figure(figsize=[5,5])
for r in [5,10,15,20,25]:
    plt.plot(r*np.cos(t),r*np.sin(t),lw=1, color='k',label=str(A))
    labelLines(plt.gca().get_lines(), zorder=3.5)
plt.draw()
```
![download (29)](https://user-images.githubusercontent.com/35923822/129475539-8f4b9ceb-50c2-4b63-bf8b-71bdf43f4e42.png)

**Comment by cphyc** [comment]
Hi,
I don't think I understand what the issue is, as if I amend your code as follows, each line is labelled by their radius
```python
In [14]: t = np.linspace(0,2*np.pi)
    ...: A = [10,25]
    ...: fig = plt.figure(figsize=[5,5])
    ...: for r in [5,10,15,20,25]:
    ...:     l, = plt.plot(r*np.cos(t),r*np.sin(t),lw=1, color='k',label=f"${r=}$")
   ....:     #                                                          ^  note that the `label=` has been modified
    ...:     labelLine(l, 0, zorder=3.5)
    ...: plt.draw()
```
![image](https://user-images.githubusercontent.com/5411875/129724422-5246ab90-4a18-46a2-9808-82731464fbf7.png)
The label that will be drawn on each line is the one provided in the `label=` keyword argument in the `plt.plot` call.

**Comment by syedhamidali** [comment]
Thanka dear.
