### ISSUE TITLE
Labels not overlapping in radians polar plot

### ISSUE THREAD

**Issue by mserouar** [cphyc/matplotlib-label-lines#54]
Hello, 

First, nice work.
However here what I have : 

![image](https://user-images.githubusercontent.com/57948061/130215442-2d2f0cba-f2a8-4f7a-a4b8-c659bf4a6935.png)

There is the snip to reproduce :

```
import csv
import numpy as np
import matplotlib.pyplot as plt

bar_colors = ['#333333', '#444444', '#555555', '#666666', '#777777', '#888888', '#999999', '#AA0000']
num_obs = len(bar_colors)

wind_direction = (2*3.14)*(np.random.random_sample(num_obs))
wind_speed = 5 * np.random.random_sample(num_obs)
number = [1,2,3,4,5,6,7,8]
wind = zip(wind_direction, wind_speed, bar_colors, number)

fig = plt.figure(figsize=(3, 3))  
ax = plt.subplot(111, polar=True)  


for w in wind:
    ax.plot((0, w[0]), (0, w[1]), c = w[2], label = str(w[3]))
    
labelLines(ax.get_lines())

fig.show()
```

Thanks a lot !

**Comment by cphyc** [comment]
Ouch, the labels are really out of place :/

**Comment by HPLegion** [comment]
Hi,

while I tried to fix this, I noticed that this problem actually arises mostly from poorly defined input (in the mathematical sense, so no offence, it took me a while to realise too :stuck_out_tongue: )

The problem is hiding here:
```python
ax.plot((0, w[0]), (0, w[1]), c = w[2], label = str(w[3]))
````
Since this is given in polar coordinates, and x takes the role of an angle, it is simply not well defined for a radius y=0.
Therefore you get away with giving an arbitrary angle (0 in your case)

However fixing this issue is relatively straight forward:
```python
ax.plot((w[0], w[0]), (0, w[1]), c = w[2], label = str(w[3]))
```
Visually the plot does not change, but by providing a "reasonable angle" (for what is meant to be a radial line), a good location for the label can be determined and everything looks great

On a side note: Thanks to the random data producing funny lines, the placement heuristic crashed repeatedly for me, I'll open a separate issue for that
