### ISSUE TITLE
Making the text transparent

### ISSUE THREAD

**Issue by abcnishant007** [cphyc/matplotlib-label-lines#93]
Is there a way to increase the transparency of the on-line text label. Currently, it is fully opaque.

P.S congrats on the awesome package!

**Comment by cphyc** [comment]
Yes, any extra argument passed to `labelLines[s]` will be passed down to a matplotlib `plt.text(…)` call. So you for example do something like
```
from labellines import labelLines
import numpy as np

x = np.linspace(0, 2*np.pi, 100)
y = np.cos(x)
line, = plt.plot(x, y, label="cos x")
labelLines(line, alpha=0.5)
```
![image](https://user-images.githubusercontent.com/5411875/170949473-eff15578-3633-478e-8954-116835871c6c.png)
This is not perfect because the outline is transparent as well, but that's a good start!

**Comment by abcnishant007** [comment]
Got it, thanks!
Please feel free to close the issue
